services:

  erp-backend-qa:

    image: indiadelhi001/erp-backend:${VERSION}

    container_name: erp-backend-qa

    restart: unless-stopped

    env_file:
      - .env.runtime

    ports:
      - "8000:8000"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s


  erp-frontend:

    image: indiadelhi001/erp-frontend:${VERSION}

    container_name: erp-frontend

    restart: unless-stopped

    depends_on:
      erp-backend-qa:
        condition: service_healthy

    environment:
      BACKEND_HOST: erp-backend-qa
      BACKEND_PORT: "8000"

    ports:
      - "3000:80"