services:
  mysql-db-qa:
    image: mysql:8.0
    container_name: mysql-db-qa
    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend-qa:
    build:
      context: ./logic

    container_name: backend-qa:v1.0
    restart: unless-stopped

    depends_on:
      mysql-db-qa:
        condition: service_healthy

    env_file:
      - .env

    ports:
      - "8000:8000"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    build:
      context: ./web

    container_name: frontend:v1.0
    restart: unless-stopped

    depends_on:
      backend-qa:
        condition: service_healthy

    environment:
      BACKEND_HOST: backend-qa
      BACKEND_PORT: "8000"

    ports:
      - "3000:80"

volumes:
  mysql_data: