services:

  erp-backend:

    image: indiadelhi001/erp-backend:${IMAGE_VERSION}

    container_name: erp-backend

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    healthcheck:

      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8000/healthz/"
        ]

      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s


  erp-frontend:

    image: indiadelhi001/erp-frontend:${IMAGE_VERSION}

    container_name: erp-frontend

    restart: unless-stopped

    depends_on:

      erp-backend:

        condition: service_healthy

    ports:
      - "3000:80"