# Generated by Django 5.2.11 on 2026-03-24 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_delivery_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynoteattachment',
            name='delivery_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.deliverynote'),
        ),
        migrations.AddField(
            model_name='deliverynoteattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotecomment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotecomment',
            name='delivery_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.deliverynote'),
        ),
        migrations.AddField(
            model_name='deliverynotecustomeracknowledgement',
            name='delivery_note',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgement', to='crm.deliverynote'),
        ),
        migrations.AddField(
            model_name='deliverynotecustomeracknowledgement',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotehistory',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotehistory',
            name='delivery_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.deliverynote'),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='delivery_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.deliverynote'),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product'),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.uom'),
        ),
        migrations.AddField(
            model_name='deliverynotereturn',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dnr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotereturn',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer'),
        ),
        migrations.AddField(
            model_name='deliverynotereturn',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dnr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotereturnattachment',
            name='delivery_note_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.deliverynotereturn'),
        ),
        migrations.AddField(
            model_name='deliverynotereturnattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotereturncomment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotereturncomment',
            name='delivery_note_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.deliverynotereturn'),
        ),
        migrations.AddField(
            model_name='deliverynotereturnhistory',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotereturnhistory',
            name='delivery_note_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.deliverynotereturn'),
        ),
        migrations.AddField(
            model_name='deliverynotereturnitem',
            name='delivery_note_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.deliverynotereturn'),
        ),
        migrations.AddField(
            model_name='deliverynotereturnitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product'),
        ),
        migrations.AddField(
            model_name='deliverynotereturnitem',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.uom'),
        ),
        migrations.AddField(
            model_name='deliverynotereturnserial',
            name='delivery_note_return_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='crm.deliverynotereturnitem'),
        ),
        migrations.AddField(
            model_name='deliverynoteserial',
            name='delivery_note_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='crm.deliverynoteitem'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiryitem',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.enquiry'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceattachment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicecomment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicecomment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.invoice'),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.taxcode'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.uom'),
        ),
        migrations.AddField(
            model_name='invoicereturn',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoice_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicereturn',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer'),
        ),
        migrations.AddField(
            model_name='invoicereturn',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='crm.invoice'),
        ),
        migrations.AddField(
            model_name='invoicereturn',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_invoice_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverynotereturn',
            name='invoice_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dn_returns', to='crm.invoicereturn'),
        ),
        migrations.AddField(
            model_name='invoicereturnattachment',
            name='invoice_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.invoicereturn'),
        ),
        migrations.AddField(
            model_name='invoicereturnattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicereturncomment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicereturncomment',
            name='invoice_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.invoicereturn'),
        ),
        migrations.AddField(
            model_name='invoicereturnhistory',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicereturnhistory',
            name='invoice_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.invoicereturn'),
        ),
        migrations.AddField(
            model_name='invoicereturnitem',
            name='invoice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.invoiceitem'),
        ),
        migrations.AddField(
            model_name='invoicereturnitem',
            name='invoice_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.invoicereturn'),
        ),
        migrations.AddField(
            model_name='invoicereturnitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product'),
        ),
        migrations.AddField(
            model_name='invoicereturnitem',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.uom'),
        ),
        migrations.AddField(
            model_name='deliverynotereturnitem',
            name='invoice_return_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.invoicereturnitem'),
        ),
        migrations.AddField(
            model_name='invoicereturnserial',
            name='invoice_return_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='crm.invoicereturnitem'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='masters.customer'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sales_rep',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__role': 'Sales Representative'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_rep_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationattachment',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationcomment',
            name='comment_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationcomment',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationhistory',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationhistory',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.taxcode'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.uom'),
        ),
        migrations.AddField(
            model_name='quotationrevision',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationrevision',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='crm.quotation'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='masters.customer'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sales_rep',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__role': 'Sales Representative'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_rep_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.salesorder'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='crm.salesorder'),
        ),
        migrations.AddField(
            model_name='salesordercomment',
            name='comment_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesordercomment',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderhistory',
            name='action_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderhistory',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.product'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.taxcode'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.uom'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverynotereturnserial',
            unique_together={('delivery_note_return_item', 'serial_no')},
        ),
        migrations.AlterUniqueTogether(
            name='invoicereturnserial',
            unique_together={('invoice_return_item', 'serial_no')},
        ),
    ]
