# Generated by Django 5.2.11 on 2026-03-24 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=100)),
                ('batch_qty', models.IntegerField()),
                ('mfg_date', models.DateField()),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BatchSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='purchase.batchnumber')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO_ID', models.CharField(editable=False, max_length=20, unique=True)),
                ('po_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Partially Received', 'Partially Received'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=30)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('payment_terms', models.CharField(blank=True, choices=[('Net 30', 'Net 30'), ('Net 45', 'Net 45'), ('Net 90', 'Net 90'), ('Credit', 'Credit'), ('Advance', 'Advance'), ('Partial Advance', 'Partial Advance'), ('On Delivery (COD)', 'On Delivery (COD)'), ('Upon Invoice', 'Upon Invoice')], max_length=50)),
                ('inco_terms', models.CharField(blank=True, choices=[('FOB', 'FOB (Free On Board)'), ('CIF', 'CIF (Cost, Insurance & Freight)'), ('EXW', 'EXW (Ex Works)'), ('DDP', 'DDP (Delivered Duty Paid)'), ('DAP', 'DAP (Delivered at Place)'), ('FCA', 'FCA (Free Carrier)'), ('CFR', 'CFR (Cost and Freight)')], max_length=50)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('INR', 'INR'), ('GBP', 'GBP'), ('SGD', 'SGD')], default='INR', max_length=10)),
                ('notes_comments', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('global_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_summary', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('total_order_value', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='purchase_orders/attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchase.purchaseorder')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='purchase.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='purchase.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('in_stock', models.IntegerField(default=0, editable=False)),
                ('qty_ordered', models.IntegerField(default=1)),
                ('insufficient_stock', models.IntegerField(default=0, editable=False)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRN_ID', models.CharField(editable=False, max_length=20, unique=True)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('supplier_dn_no', models.CharField(blank=True, max_length=100)),
                ('supplier_invoice_no', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Partially Returned', 'Partially Returned'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_receipts', to=settings.AUTH_USER_MODEL)),
                ('po_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_receipts', to='purchase.purchaseorder')),
                ('qc_done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_stock_receipts', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_stock_receipts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stock_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockReceiptAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stock_receipts/attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('stock_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchase.stockreceipt')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockReceiptComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='purchase.stockreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='StockReceiptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='purchase.stockreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='StockReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('uom', models.CharField(blank=True, editable=False, max_length=50)),
                ('qty_ordered', models.IntegerField(default=0, editable=False)),
                ('qty_received', models.IntegerField(default=0)),
                ('accepted_qty', models.IntegerField(default=0)),
                ('rejected_qty', models.IntegerField(default=0, editable=False)),
                ('qty_returned', models.IntegerField(default=0, editable=False)),
                ('stock_dim', models.CharField(choices=[('None', 'None'), ('Serial', 'Serial'), ('Batch', 'Batch')], default='None', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product')),
                ('stock_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.stockreceipt')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('stock_receipt_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='purchase.stockreceiptitem')),
            ],
        ),
        migrations.AddField(
            model_name='batchnumber',
            name='stock_receipt_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_numbers', to='purchase.stockreceiptitem'),
        ),
        migrations.CreateModel(
            name='StockReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRN_ID', models.CharField(editable=False, max_length=20, unique=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Partially Returned', 'Partially Returned'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('original_purchased_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('global_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('return_subtotal', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('global_discount_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('amount_to_recover', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_returns', to=settings.AUTH_USER_MODEL)),
                ('grn_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_returns', to='purchase.stockreceipt')),
                ('po_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_returns', to='purchase.purchaseorder')),
                ('return_initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_returns', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.supplier')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_returns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockReturnAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stock_returns/attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('stock_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchase.stockreturn')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockReturnComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='purchase.stockreturn')),
            ],
        ),
        migrations.CreateModel(
            name='StockReturnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='purchase.stockreturn')),
            ],
        ),
        migrations.CreateModel(
            name='StockReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('qty_ordered', models.IntegerField(default=0, editable=False)),
                ('qty_rejected', models.IntegerField(default=0, editable=False)),
                ('qty_returned', models.IntegerField(default=0)),
                ('return_reason', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product')),
                ('stock_receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.stockreceiptitem')),
                ('stock_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.stockreturn')),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumberReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('stock_return_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='purchase.stockreturnitem')),
            ],
        ),
    ]
