# Generated by Django 5.2.11 on 2026-04-21 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
        ('purchase', '0002_remove_serialnumberreturn_serial_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynoteserial',
            name='serial_no',
        ),
        migrations.AddField(
            model_name='deliverynoteserial',
            name='batch_serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.batchserialnumber'),
        ),
        migrations.AddField(
            model_name='deliverynoteserial',
            name='serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.serialnumber'),
        ),
    ]
