# Generated by Django 5.2.11 on 2026-04-21 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_deliverynoteserial_serial_no_and_more'),
        ('purchase', '0002_remove_serialnumberreturn_serial_no_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoicereturnserial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoicereturnserial',
            name='batch_serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.batchserialnumber'),
        ),
        migrations.AddField(
            model_name='invoicereturnserial',
            name='serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.serialnumber'),
        ),
        migrations.AddConstraint(
            model_name='invoicereturnserial',
            constraint=models.UniqueConstraint(fields=('invoice_return_item', 'serial'), name='unique_invoice_return_serial'),
        ),
        migrations.AddConstraint(
            model_name='invoicereturnserial',
            constraint=models.UniqueConstraint(fields=('invoice_return_item', 'batch_serial'), name='unique_invoice_return_batch_serial'),
        ),
        migrations.RemoveField(
            model_name='invoicereturnserial',
            name='serial_no',
        ),
    ]
