# Generated by Django 5.2.11 on 2026-06-16 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_assetsaleapprover_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_category', models.CharField(choices=[('Machinery & Equipments', 'Machinery & Equipments'), ('Building & Structures', 'Building & Structures'), ('Vehicles', 'Vehicles'), ('IT & Electronics', 'IT & Electronics'), ('Furniture', 'Furniture')], max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('custom_floor', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_book_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='asset_InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('sector_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Foreign', 'Foreign')], max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('irdai_license_no', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='asset_ResponsibleEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('responsibility_type', models.CharField(choices=[('Individual', 'Individual'), ('Department', 'Department'), ('Committee', 'Committee')], max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='bankreconciliation',
            table=None,
        ),
        migrations.CreateModel(
            name='AssetInsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100)),
                ('policy_type', models.CharField(max_length=100)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('policy_start_date', models.DateField()),
                ('policy_end_date', models.DateField()),
                ('renewal_reminder_days', models.IntegerField(choices=[(30, '30 Days'), (45, '45 Days'), (60, '60 Days'), (90, '90 Days')])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='finance.asset')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.asset_insurancecompany')),
                ('insured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.asset_responsibleentity')),
            ],
        ),
        migrations.CreateModel(
            name='asset_PremiumPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_premium_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_frequency', models.CharField(choices=[('Annually', 'Annually'), ('Semi-Annually', 'Semi-Annually'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly'), ('One Time', 'One Time')], max_length=50)),
                ('premium_due_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('Cheque', 'Cheque'), ('Online Portal', 'Online Portal'), ('Auto-Debit', 'Auto-Debit'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], max_length=50)),
                ('gst_on_premium', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_premium_incl_gst', models.DecimalField(decimal_places=2, max_digits=15)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_payments', to='finance.assetinsurancepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='asset_PolicyLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.asset')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.assetinsurancepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='asset_PolicyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance.assetinsurancepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='asset_PolicyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='finance.assetinsurancepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='asset_PolicyAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='insurance_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.assetinsurancepolicy')),
            ],
        ),
    ]
