# Generated by Django 5.2.11 on 2026-06-10 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Contact number must be digits only, optionally starting with +.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
