# Generated by Django 5.2.11 on 2026-05-19 08:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_invoicereturnserial_unique_together_and_more'),
        ('finance', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formreceipt_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('purchase_order_no', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Posted', 'Posted to Inventory'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.approvedby')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.requestedby')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.supplier')),
            ],
            options={
                'verbose_name': 'Form Receivable',
                'verbose_name_plural': 'Form Receivables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormReceivableAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='form_receivable/attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('form_receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.formreceivable')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormReceivableComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('form_receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='finance.formreceivable')),
            ],
        ),
        migrations.CreateModel(
            name='FormReceivableHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Created', 'Created'), ('Updated', 'Updated'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Posted', 'Posted')], max_length=100)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('form_receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance.formreceivable')),
            ],
        ),
        migrations.CreateModel(
            name='FormReceivableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=20)),
                ('ordered_qty', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_qty', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('rejected_qty', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.batchno')),
                ('form_receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.formreceivable')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.warehousedet')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('revenue_type', models.CharField(choices=[('Product Sales', 'Product Sales'), ('Service Income', 'Service Income'), ('Rental Income', 'Rental Income')], max_length=50)),
                ('revenue_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_type', models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT'), ('TDS', 'TDS')], default='GST', max_length=20)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('payment_received', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('Cheque', 'Cheque'), ('NEFT', 'NEFT'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], max_length=20, null=True)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20)),
                ('ledger_posting', models.CharField(blank=True, choices=[('Sales Ledger', 'Sales Ledger'), ('Service Income Ledger', 'Service Income Ledger'), ('Rental Income Ledger', 'Rental Income Ledger'), ('Miscellaneous Income Ledger', 'Miscellaneous Income Ledger'), ('Other Operating Income Ledger', 'Other Operating Income Ledger')], max_length=50, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_revenues', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.invoice')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.salesorder')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_revenues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='revenues/attachments/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.revenue')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='finance.revenue')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance.revenue')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15)),
                ('tax_type', models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT'), ('TDS', 'TDS')], default='GST', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15)),
                ('ledger_posting', models.CharField(blank=True, choices=[('Sales Ledger', 'Sales Ledger'), ('Service Income Ledger', 'Service Income Ledger'), ('Rental Income Ledger', 'Rental Income Ledger'), ('Miscellaneous Income Ledger', 'Miscellaneous Income Ledger'), ('Other Operating Income Ledger', 'Other Operating Income Ledger')], max_length=50, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.product')),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.revenue')),
            ],
        ),
    ]
