# Generated by Django 6.0.2 on 2026-05-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_formreceivable_formreceivableattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50, unique=True)),
                ('report_type', models.CharField(choices=[('INCOME', 'Income Statement'), ('BALANCE', 'Balance Sheet'), ('CASHFLOW', 'Cash Flow')], max_length=20)),
                ('reporting_currency', models.CharField(max_length=10)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('level_of_detail', models.CharField(choices=[('SUMMARY', 'Summary'), ('DETAILED', 'Detailed')], max_length=10)),
                ('comparison_period', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='trialbalancehistory',
            old_name='action',
            new_name='action_by',
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='include_unposted_txns',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='level_of_detail',
            field=models.CharField(choices=[('summary', 'Summary'), ('grouped', 'Grouped'), ('detailed', 'Detailed')], default='Detailed', max_length=20),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
        migrations.CreateModel(
            name='FinancialLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comparison_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ledger_posting', models.CharField(max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.financialreport')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_by', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='finance.financialreport')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='finance.financialreport')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('operating_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cash_from_operations', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cash_from_investing', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cash_from_financing', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='finance.financialreport')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('performed_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance.financialreport')),
            ],
        ),
    ]
