# Generated by Django 5.2.11 on 2026-06-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_approver_assetsalebuyer_form_receivable_approvedby_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assetsale',
            table=None,
        ),
    ]
