# Generated by Django 5.2.11 on 2026-06-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_assetsale_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assetsaleapprover',
            table=None,
        ),
        migrations.AlterModelTable(
            name='assetsaleattachment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='assetsalebuyer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='assetsalecomment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='assetsalehistory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='assetsaleitem',
            table=None,
        ),
    ]
