# Generated by Django 5.2.11 on 2026-04-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialnumberreturn',
            name='serial_no',
        ),
        migrations.AddField(
            model_name='serialnumberreturn',
            name='batch_serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.batchserialnumber'),
        ),
        migrations.AddField(
            model_name='serialnumberreturn',
            name='serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.serialnumber'),
        ),
    ]
